config/routes.rb
CultureRun::Application.routes.draw do
  resources :events
  resource :users

  root :to => 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :content, :name, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :gender
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_resource

  def show
    #@user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def find_resource

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.haml
.questions-rom{ :data_ng_controller => 'formsController' }
  %form.form-horizontal{ :name => 'myForm' }
    .control-group{ :data_ng_class => '{error: myForm.subject.$error.required, warning: myForm.subject.$error.minlength, success: myForm.subject.$valid}' }
      %input{:name => 'subject', :required => true, :type => 'text',
        :data_ng_model => 'questionSubject',
        :data_ng_pattern => '/^(What|When|How|Which|Where|Who|Why|Can)/',
        :data_ng_minlength => "15" }
      %br
      %div.guidance
        %div{ :data_ng_class => "{'text-error': myForm.subject.$error.required, 'text-success': !myForm.subject.$error.required}" }
          %i.icon-minus
          %i.icon-ok
          Question can't be blank.
        %div{ :data_ng_class => "{'text-error': myForm.subject.$error.required,
              'text-warning': myForm.subject.$error.minlength,
              'text-success': (!myForm.subject.$error.minlength && !myForm.subject.$error.required) }" }
          %i.icon-minus
          %i.icon-ok
          Question is too short! (Minimum 15 characters)
        %div{ :data_ng_class => "{'text-error': myForm.subject.$error.required,
              'text-warning': (!myForm.subject.$error.minlength && myForm.subject.$error.pattern),
              'text-success': (!myForm.subject.$error.pattern && !myForm.subject.$error.required)}" }
          %i.icon-minus
          %i.icon-ok
          Please ask a valid question.
          %i
            %small
              %b Tip:
              Start with "What", "Who", "When" etc. End the question with a '?'


.page-header
  %h1 Upcomming Events
  %p.lead Stay tuned for the latest upcomming events!

%table.table
  %tr
    %th Name
    %th Title
    %th Content
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.name
      %td= event.title
      %td= event.content
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }


= link_to 'New Event', new_event_path

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.haml
%p.lead
  = @event.name
  %br
  %small= @event.title

= @event.content

= link_to 'Edit', edit_event_path(@event)
= link_to 'Back', events_path

app/views/layouts/application.html.haml
!!! 5
%html{ :'ng-app' => '' }
  %head
    %title Culture Run
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    :css
      .text-error .icon-ok, .text-warning .icon-ok { display: none; }
      .text-success .icon-minus { display: none; }

  %body
    .navbar
      .navbar-inner
        = link_to 'Culture Run', root_path, :class => 'brand'
        %ul.nav
          %li= link_to 'Learn', '#'
          %li= link_to 'Teach', '#'
          %li= link_to 'Host', '#'
          %li= link_to 'List', '#'

    .container
      - if notice.present?
        .alert= notice
      = yield

      = params.inspect

app/views/users/_form.html.haml
= form_for(@user) do |f|
  -if @user.errors.any?
    .error_explanation
      #{pluralize(@user.errors.count, 'error')} prohibited this event from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

app/views/users/new.html.haml
%h1 New User

= render 'form'